"""m13 llp module

Revision ID: 262fda290a37
Revises: 2688c17513df
Create Date: 2026-07-12 08:52:02.840009
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '262fda290a37'
down_revision = '2688c17513df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llp',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('llpin', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('fy_end_month', sa.Integer(), nullable=False),
    sa.Column('fy_end_day', sa.Integer(), nullable=False),
    sa.Column('total_contribution', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llp_firm_id'), 'llp', ['firm_id'], unique=False)
    op.create_table('llp_partner',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('llp_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dpin', sa.String(length=8), nullable=True),
    sa.Column('is_designated', sa.Boolean(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('cessation_date', sa.Date(), nullable=True),
    sa.Column('contribution', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('profit_share_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['llp_id'], ['llp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llp_partner_firm_id'), 'llp_partner', ['firm_id'], unique=False)
    op.create_index(op.f('ix_llp_partner_llp_id'), 'llp_partner', ['llp_id'], unique=False)
    op.create_table('llp_working_paper',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('llp_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('form', sa.Enum('form11', 'form8', name='llp_form'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalized', name='working_paper_status'), nullable=False),
    sa.Column('srn', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['llp_id'], ['llp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llp_id', 'fy', 'form')
    )
    op.create_index(op.f('ix_llp_working_paper_firm_id'), 'llp_working_paper', ['firm_id'], unique=False)
    op.create_index(op.f('ix_llp_working_paper_llp_id'), 'llp_working_paper', ['llp_id'], unique=False)
    # ### end Alembic commands ###

    # LLPIN unique per firm among NON-deleted LLPs (same discipline as company CIN)
    op.execute(
        "CREATE UNIQUE INDEX uq_llp_firm_llpin ON llp (firm_id, llpin) "
        "WHERE deleted_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_llp_firm_llpin")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llp_working_paper_llp_id'), table_name='llp_working_paper')
    op.drop_index(op.f('ix_llp_working_paper_firm_id'), table_name='llp_working_paper')
    op.drop_table('llp_working_paper')
    op.drop_index(op.f('ix_llp_partner_llp_id'), table_name='llp_partner')
    op.drop_index(op.f('ix_llp_partner_firm_id'), table_name='llp_partner')
    op.drop_table('llp_partner')
    op.drop_index(op.f('ix_llp_firm_id'), table_name='llp')
    op.drop_table('llp')
    # ### end Alembic commands ###
