"""m11 practice masters

Revision ID: 2688c17513df
Revises: 9ed858c5e94d
Create Date: 2026-07-12 08:29:24.949310
"""
from alembic import op
import sqlalchemy as sa


revision = '2688c17513df'
down_revision = '9ed858c5e94d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditor',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('firm_name', sa.String(length=200), nullable=False),
    sa.Column('frn', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'frn')
    )
    op.create_index(op.f('ix_auditor_firm_id'), 'auditor', ['firm_id'], unique=False)
    op.create_table('pcs_professional',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('membership_no', sa.String(length=20), nullable=False),
    sa.Column('cop_no', sa.String(length=20), nullable=True),
    sa.Column('firm_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'membership_no')
    )
    op.create_index(op.f('ix_pcs_professional_firm_id'), 'pcs_professional', ['firm_id'], unique=False)
    op.create_table('auditor_appointment',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('appointed_from_fy', sa.Integer(), nullable=False),
    sa.Column('appointed_to_fy', sa.Integer(), nullable=True),
    sa.Column('adt1_srn', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['auditor.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_appointment_auditor_id'), 'auditor_appointment', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_auditor_appointment_company_id'), 'auditor_appointment', ['company_id'], unique=False)
    op.create_index(op.f('ix_auditor_appointment_firm_id'), 'auditor_appointment', ['firm_id'], unique=False)
    op.create_table('dsc_token',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('director_id', sa.UUID(), nullable=True),
    sa.Column('token_color', sa.String(length=30), nullable=True),
    sa.Column('token_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsc_token_firm_id'), 'dsc_token', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsc_token_firm_id'), table_name='dsc_token')
    op.drop_table('dsc_token')
    op.drop_index(op.f('ix_auditor_appointment_firm_id'), table_name='auditor_appointment')
    op.drop_index(op.f('ix_auditor_appointment_company_id'), table_name='auditor_appointment')
    op.drop_index(op.f('ix_auditor_appointment_auditor_id'), table_name='auditor_appointment')
    op.drop_table('auditor_appointment')
    op.drop_index(op.f('ix_pcs_professional_firm_id'), table_name='pcs_professional')
    op.drop_table('pcs_professional')
    op.drop_index(op.f('ix_auditor_firm_id'), table_name='auditor')
    op.drop_table('auditor')
    # ### end Alembic commands ###
