"""m6 document templates and library

Revision ID: 4dd1680921de
Revises: 8be66146b918
Create Date: 2026-07-11 19:26:34.715033
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4dd1680921de'
down_revision = '8be66146b918'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_template',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('governing_reference', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('validated_membership_no', sa.String(length=50), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('generated_document',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('letterhead', sa.Enum('company', 'pcs', 'none', name='letterhead'), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['doc_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_document_company_id'), 'generated_document', ['company_id'], unique=False)
    op.create_index(op.f('ix_generated_document_firm_id'), 'generated_document', ['firm_id'], unique=False)
    op.drop_index(op.f('uq_company_firm_cin'), table_name='company', postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_company_firm_cin'), 'company', ['firm_id', 'cin'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_generated_document_firm_id'), table_name='generated_document')
    op.drop_index(op.f('ix_generated_document_company_id'), table_name='generated_document')
    op.drop_table('generated_document')
    op.drop_table('doc_template')
    # ### end Alembic commands ###
