"""phase 1 schema

Revision ID: 8be66146b918
Revises: 
Create Date: 2026-07-11 17:48:42.962195
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '8be66146b918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_firm_id'), 'activity_log', ['firm_id'], unique=False)
    op.create_table('compliance_rule',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('roc', 'income_tax', 'gst', name='rule_category'), nullable=False),
    sa.Column('obligation_name', sa.String(length=300), nullable=False),
    sa.Column('form_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('firm',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'name')
    )
    op.create_index(op.f('ix_industry_firm_id'), 'industry', ['firm_id'], unique=False)
    op.create_table('invitation',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('partner', 'manager', 'executive', 'viewer', name='user_role'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_invitation_firm_id'), 'invitation', ['firm_id'], unique=False)
    op.create_table('professional_group',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'name')
    )
    op.create_index(op.f('ix_professional_group_firm_id'), 'professional_group', ['firm_id'], unique=False)
    op.create_table('rule_extension',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('circular_ref', sa.String(length=200), nullable=False),
    sa.Column('circular_date', sa.Date(), nullable=False),
    sa.Column('applies_fy', sa.Integer(), nullable=False),
    sa.Column('applies_predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extended_due_date', sa.Date(), nullable=False),
    sa.Column('signed_off_by', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_extension_rule_id'), 'rule_extension', ['rule_id'], unique=False)
    op.create_table('rule_version',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signed_off_by', sa.String(length=200), nullable=False),
    sa.Column('signoff_note', sa.Text(), nullable=True),
    sa.Column('source_document_ref', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rule.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_no')
    )
    op.create_index(op.f('ix_rule_version_rule_id'), 'rule_version', ['rule_id'], unique=False)
    op.create_table('user',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('partner', 'manager', 'executive', 'viewer', name='user_role'), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'email')
    )
    op.create_index(op.f('ix_user_firm_id'), 'user', ['firm_id'], unique=False)
    op.create_table('company',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('professional_group_id', sa.UUID(), nullable=True),
    sa.Column('industry_id', sa.UUID(), nullable=True),
    sa.Column('fy_end_month', sa.Integer(), nullable=False),
    sa.Column('fy_end_day', sa.Integer(), nullable=False),
    sa.Column('agm_date', sa.Date(), nullable=True),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('authorised_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('subscribed_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paidup_capital', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['professional_group_id'], ['professional_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_firm_id'), 'company', ['firm_id'], unique=False)
    op.create_table('calendar_row',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Enum('company', 'director', name='subject_type'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('occurrence_label', sa.String(length=30), nullable=False),
    sa.Column('computed_due_date', sa.Date(), nullable=True),
    sa.Column('override_date', sa.Date(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('extension_id', sa.UUID(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'filed', 'not_applicable', name='row_status'), nullable=False),
    sa.Column('srn', sa.String(length=50), nullable=True),
    sa.Column('filed_offline_ack', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('needs_review_reason', sa.Enum('missing_anchor', 'applicability_unknown', 'rule_revised', name='needs_review_reason'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['extension_id'], ['rule_extension.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fy', 'rule_version_id', 'subject_id', 'occurrence_label')
    )
    op.create_index(op.f('ix_calendar_row_company_id'), 'calendar_row', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_row_firm_id'), 'calendar_row', ['firm_id'], unique=False)
    op.create_table('company_fy_attributes',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('has_tan', sa.Boolean(), nullable=True),
    sa.Column('has_gst_registration', sa.Boolean(), nullable=True),
    sa.Column('has_transfer_pricing', sa.Boolean(), nullable=True),
    sa.Column('has_outstanding_receipts', sa.Boolean(), nullable=True),
    sa.Column('has_msme_dues_over_45d', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fy')
    )
    op.create_index(op.f('ix_company_fy_attributes_company_id'), 'company_fy_attributes', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_fy_attributes_firm_id'), 'company_fy_attributes', ['firm_id'], unique=False)
    op.create_table('director',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('din', sa.String(length=8), nullable=True),
    sa.Column('din_status', sa.String(length=50), nullable=True),
    sa.Column('din_allocation_date', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('cessation_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_company_id'), 'director', ['company_id'], unique=False)
    op.create_index(op.f('ix_director_firm_id'), 'director', ['firm_id'], unique=False)
    op.create_table('shareholder',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=True),
    sa.Column('shares', sa.Numeric(precision=18, scale=0), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholder_company_id'), 'shareholder', ['company_id'], unique=False)
    op.create_index(op.f('ix_shareholder_firm_id'), 'shareholder', ['firm_id'], unique=False)
    op.create_table('director_disclosure',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('director_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('mbp1_received', sa.Date(), nullable=True),
    sa.Column('dir8_received', sa.Date(), nullable=True),
    sa.Column('dir2_received', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_id', 'fy')
    )
    op.create_index(op.f('ix_director_disclosure_director_id'), 'director_disclosure', ['director_id'], unique=False)
    op.create_index(op.f('ix_director_disclosure_firm_id'), 'director_disclosure', ['firm_id'], unique=False)
    op.create_table('reminder_config',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('calendar_row_id', sa.UUID(), nullable=False),
    sa.Column('days_before', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('extra_emails', sa.ARRAY(sa.String(length=320)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_row_id'], ['calendar_row.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_row_id')
    )
    op.create_index(op.f('ix_reminder_config_firm_id'), 'reminder_config', ['firm_id'], unique=False)
    op.create_table('reminder_dispatch',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('reminder_config_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'failed', 'dead', name='dispatch_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.ForeignKeyConstraint(['reminder_config_id'], ['reminder_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_dispatch_firm_id'), 'reminder_dispatch', ['firm_id'], unique=False)
    op.create_index(op.f('ix_reminder_dispatch_reminder_config_id'), 'reminder_dispatch', ['reminder_config_id'], unique=False)
    # ### end Alembic commands ###

    # --- Hand-written, charter-mandated (do not remove) ---
    # CIN unique per firm among NON-deleted companies (REVIEW F8):
    op.execute(
        "CREATE UNIQUE INDEX uq_company_firm_cin ON company (firm_id, cin) "
        "WHERE deleted_at IS NULL"
    )
    # Append-only enforcement (charter C11) and immutable rule versions (PRD §7).
    # Grants apply when the runtime app role exists (created at deploy time).
    op.execute("""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'praxis_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO praxis_app;
        REVOKE UPDATE, DELETE ON activity_log FROM praxis_app;
        REVOKE UPDATE ON rule_version FROM praxis_app;
        REVOKE DELETE ON rule_version FROM praxis_app;
    END IF;
END
$$;
""")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_company_firm_cin")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_dispatch_reminder_config_id'), table_name='reminder_dispatch')
    op.drop_index(op.f('ix_reminder_dispatch_firm_id'), table_name='reminder_dispatch')
    op.drop_table('reminder_dispatch')
    op.drop_index(op.f('ix_reminder_config_firm_id'), table_name='reminder_config')
    op.drop_table('reminder_config')
    op.drop_index(op.f('ix_director_disclosure_firm_id'), table_name='director_disclosure')
    op.drop_index(op.f('ix_director_disclosure_director_id'), table_name='director_disclosure')
    op.drop_table('director_disclosure')
    op.drop_index(op.f('ix_shareholder_firm_id'), table_name='shareholder')
    op.drop_index(op.f('ix_shareholder_company_id'), table_name='shareholder')
    op.drop_table('shareholder')
    op.drop_index(op.f('ix_director_firm_id'), table_name='director')
    op.drop_index(op.f('ix_director_company_id'), table_name='director')
    op.drop_table('director')
    op.drop_index(op.f('ix_company_fy_attributes_firm_id'), table_name='company_fy_attributes')
    op.drop_index(op.f('ix_company_fy_attributes_company_id'), table_name='company_fy_attributes')
    op.drop_table('company_fy_attributes')
    op.drop_index(op.f('ix_calendar_row_firm_id'), table_name='calendar_row')
    op.drop_index(op.f('ix_calendar_row_company_id'), table_name='calendar_row')
    op.drop_table('calendar_row')
    op.drop_index(op.f('ix_company_firm_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_user_firm_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rule_version_rule_id'), table_name='rule_version')
    op.drop_table('rule_version')
    op.drop_index(op.f('ix_rule_extension_rule_id'), table_name='rule_extension')
    op.drop_table('rule_extension')
    op.drop_index(op.f('ix_professional_group_firm_id'), table_name='professional_group')
    op.drop_table('professional_group')
    op.drop_index(op.f('ix_invitation_firm_id'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_industry_firm_id'), table_name='industry')
    op.drop_table('industry')
    op.drop_table('firm')
    op.drop_table('compliance_rule')
    op.drop_index(op.f('ix_activity_log_firm_id'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
