"""m10 meetings

Revision ID: 9ed858c5e94d
Revises: e0efaa72d48a
Create Date: 2026-07-12 08:12:03.376285
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9ed858c5e94d'
down_revision = 'e0efaa72d48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fy', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.Enum('board', 'committee', 'egm', 'agm', name='meeting_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'held', name='meeting_status'), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('meeting_time', sa.String(length=20), nullable=False),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('notice_date', sa.Date(), nullable=True),
    sa.Column('chairperson', sa.String(length=200), nullable=True),
    sa.Column('agenda_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participant_director_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_company_id'), 'meeting', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_firm_id'), 'meeting', ['firm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_firm_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_company_id'), table_name='meeting')
    op.drop_table('meeting')
    # ### end Alembic commands ###
