"""m9 statutory registers, phase 2 rule categories

Revision ID: e0efaa72d48a
Revises: 4dd1680921de
Create Date: 2026-07-12 07:58:19.871749
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e0efaa72d48a'
down_revision = '4dd1680921de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('register_type', sa.Enum('members', 'debenture_holders', 'share_transfers', 'directors_kmp', 'charges', 'investments', 'loans_guarantees', 'related_party_contracts', 'duplicate_share_certs', 'beneficial_interest', 'deposits', 'sweat_equity', 'esop', 'buy_back', name='register_type'), nullable=False),
    sa.Column('entry_key', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_key', 'version_no')
    )
    op.create_index(op.f('ix_register_entry_company_id'), 'register_entry', ['company_id'], unique=False)
    op.create_index(op.f('ix_register_entry_entry_key'), 'register_entry', ['entry_key'], unique=False)
    op.create_index(op.f('ix_register_entry_firm_id'), 'register_entry', ['firm_id'], unique=False)
    op.create_index(op.f('ix_register_entry_register_type'), 'register_entry', ['register_type'], unique=False)
    # ### end Alembic commands ###

    # --- Hand-written, charter/PRD-mandated (do not remove) ---
    # Phase 2 rule categories (PRD §5). ADD VALUE needs autocommit.
    with op.get_context().autocommit_block():
        for value in ("fema", "pf", "esic", "esop"):
            op.execute(f"ALTER TYPE rule_category ADD VALUE IF NOT EXISTS '{value}'")
    # Registers are legal records: append-only at the DB layer (PRD §8),
    # same enforcement as activity_log (C11).
    op.execute("""
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'praxis_app') THEN
        GRANT SELECT, INSERT ON register_entry TO praxis_app;
        REVOKE UPDATE, DELETE ON register_entry FROM praxis_app;
    END IF;
END
$$;
""")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_entry_register_type'), table_name='register_entry')
    op.drop_index(op.f('ix_register_entry_firm_id'), table_name='register_entry')
    op.drop_index(op.f('ix_register_entry_entry_key'), table_name='register_entry')
    op.drop_index(op.f('ix_register_entry_company_id'), table_name='register_entry')
    op.drop_table('register_entry')
    # ### end Alembic commands ###
